name: etlegacy
version: "v2.81.1"
summary: FPS Game
description: |
  Welcome to ET: Legacy, an open source project that aims to create a fully compatible client
  and server for the popular online FPS game Wolfenstein: Enemy Territory - whose gameplay
  is still considered unmatched by many, despite its great age.

base: core18
compression: lzo
confinement: devmode
grade: devel

apps:
  etl:
    command: &_command run
    plugs: &_plugs
      - opengl
      - wayland
      - hardware-observe
      - audio-playback
      - joystick
      - network
    environment: &_environment
      PULSE_SERVER: unix:$XDG_RUNTIME_DIR/../pulse/native
      PULSE_SYSTEM: 1
      PULSE_RUNTIME_PATH: /var/run/pulse
      LD_LIBRARY_PATH: ${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio

  etl-ded:
    command: run-ded
    plugs:
      - hardware-observe
      - network
      - network-bind
    environment:
      LD_LIBRARY_PATH: ${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}

  daemon:
    daemon: simple
    restart-delay: 3s
    restart-condition: always
    command: *_command
    plugs: *_plugs
    environment: *_environment

environment:
  # Other, generally useful environment settings...
  # XDG config
  XDG_CACHE_HOME:  $SNAP_USER_COMMON/.cache
  XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
  XDG_CONFIG_DIRS: $SNAP/etc/xdg
  XDG_DATA_DIRS:   $SNAP/usr/local/share:$SNAP/usr/share
  # XKB config
  XKB_CONFIG_ROOT: $SNAP/usr/share/X11/xkb

# The `layout` ensures that files can be found by applications where they are expected by the toolkit or application.
layout:
  /usr/share/libdrm:
    bind: $SNAP/graphics/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/graphics/drirc.d
  # Other, generally useful paths
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/sounds:
    bind: $SNAP/usr/share/sounds
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

parts:
  etl:
    plugin: dump
    source-type: tar
    source: https://github.com/etlegacy/etlegacy/archive/refs/tags/v2.81.1.tar.gz
    build-packages:
      - g++
      - gcc
      - make
      - libcurl4-openssl-dev
      - libsdl2-dev
      - liblua5.3-dev
      - libopenal-dev
      - libtheora-dev
      - libglew-dev
      - libogg-dev
      - libvorbis-dev
      - libgl1-mesa-dev
      - freeglut3-dev
      - zlib1g-dev
      - libminizip-dev
      - libturbojpeg0-dev
      - libssl-dev
      - libjson-c-dev
      - libfreetype6-dev
      - libpng-dev
      - libsqlite3-dev
      - libx11-dev	
      - libc6-dev
      - nasm
      - zip

    stage-packages:
      - libsdl2-2.0-0
      - libjson-c3
      - libcurl4
      - libminizip1
      - libtheora-bin
      - libvorbisfile3
      - libglew2.0
      - libgl1
      - libglu1-mesa
      - freeglut3
      - libjpeg8
      - libstdc++6
      - liblua5.3-0
      - libsqlite3-0
      - wget

